1=Saidi and Kollektivet - Martin, Marika, Olof, Daniel, Maria, Magnus and Erik
2=Saidi and Kollektivet - Mathias, Daniel, Magnus and Marika
3=Saidi and Kollektivet - Magnus, Daniel, Olof, Mathias, Erik and Maria
4=Saidi and Kollektivet - Olof, Erik, Maria, Magnus and Daniel
7=Saidi and Kollektivet - Daniel, Mathias, Rasmus, Olof, Magnus and Maria
5=Saidi and Kollektivet - Magnus, Maria, Mathias, Rasmus, Olof and Daniel
6=Saidi and Kollektivet - Magnus, Maria, Mathias, Rasmus, Olof and Daniel
10=Saidi and Kollektivet - Mikael, Mathias, Olof, Daniel, Rasmus and Kristina
8=Saidi and Kollektivet - Kristina, Rasmus, Mathias, Daniel and Olof
9=Saidi and Kollektivet - Rasmus, Daniel, Kristina, Olof and Mathias
live_1=Saidi and Kollektivet - Olof, Kristina, Daniel, Mathias, Rasmus and Mikael
live_2=Saidi and Kollektivet - Olof, Kristina, Daniel, Mathias, Rasmus and Mikael
live_3=Saidi and Kollektivet - Rasmus, Olof, Mathias, Daniel and Mikael
live_4=Saidi and Kollektivet - Mikael, Daniel, Mathias and Olof
live_5=Saidi and Kollektivet - Mikael, Daniel, Mathias and Olof