name: Republish

# Run at 12:01 pm every day.
on:
  schedule:
    - cron: '1 12 * * *'
  workflow_dispatch:
    
# Define the job and its build steps
jobs:
  trigger_rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url  https://api.github.com/repos/danielsaidi/website_danielsaidi/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          # You must setup a personal access token with repo
          # access, since GitHub does not yet support server
          # to server page builds.
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
